### PR TITLE
Add DarkMode toggling

### LINKED ISSUE #56: Add dark mode switch support
Add actions / reducers for dark mode support

It also would be nice to detect dark / light mode preference from the browser to set a default

Related conveyor issue:
https://github.com/autoinvent/conveyor/issues/98

### PR DESCRIPTION
**Pull request by DanielHall977**
resolves #56 

Adds reducer to support dark mode.

related to: https://github.com/autoinvent/conveyor/issues/98

### CODE REVIEW

**Comment by itechify** [comment]
Could we change the name to `userPreferences` which has a `darkMode` property? This would future proof us for any new preference ideas + saving the user preferences to local storage #58.

Also, as mentioned in #56, you should look into setting the default dark mode preference to the system setting. See https://ourcodeworld.com/articles/read/1114/how-to-detect-if-the-user-prefers-a-light-or-dark-color-schema-in-the-browser-with-javascript-and-css

It looks like you may be able to do something like: 
```
export const initState = {
   darkMode: window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches
}
```

**Comment by DanielHall977** [comment]
I'll get on those changes.

**Comment by DanielHall977** [comment]
Done, added the match media stuff. Don't know how well it works.

**Comment by itechify** [comment]
Looks good now. We may want to add the action to the [getActions](https://github.com/autoinvent/conveyor-redux/blob/master/src/utils/getActions.ts) function still though... @davidism and I need to have a discussion about this

**Comment by DanielHall977** [comment]
Isn't getActions schema and modelname specific?

**Comment by itechify** [comment]
> Isn't getActions schema and modelname specific?

Yes, so it wouldn't really make much sense given the context of this existing in a nav...at least not in any model detail/index/create pages. All other actions are provided to each of the models though, so should this be the odd one out? I'd say so, but I'd like to consult David first on what he thinks.

**Pull request merged**
